version: '3.8'

services:
  api:
    image: ninepiece2/emailservice-api:latest
    container_name: EmailService-API
    ports:
      - "8443:8443"
    volumes:
      - /root/certs:/https:ro
    environment:
      - ASPNETCORE_URLS=https://*:8443;http://*:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ssl.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/ssl.key
      - AccessToken=${ACCESS_TOKEN}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Jwt:Key=${JWT_KEY}
    command: ["dotnet", "EmailService-API.dll"]
    restart: always