name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./EmailService-API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/emailservice-api:latest

  deploy:
    runs-on: self-hosted
    needs: build  
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull latest Docker images
        run: docker-compose pull

      - name: Remove Old Continer
        run: docker-compose down

      - name: Deploy with Docker Compose
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          ASPNETCORE_ENVIRONMENT: Production
        run: docker-compose up -d